version: '2'
services:
    rails:
      build: ./rails
      container_name: rails
      links:
        - "mysql"
      ports:
        - "80:8080"
      volumes:
        - ../:/usr/src/app
    mysql:
      build: ./mysql
      container_name: mysql
      expose:
        - "3306"
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: password
      volumes:
        - ./data/mysql:/var/lib/mysql